In [41]:
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
#Colocar libreria para poder graficar

In [114]:

h=0.1
ti=np.arange(100,100)
theta=np.zeros((100,100))
theta[0]=10
w=np.linspace(10,20,11)
v=np.zeros((10,10))


In [106]:
print(theta)

[[10. 10. 10. ... 10. 10. 10.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]]


In [89]:

for v in range(10):
    v[ti+1]=v[ti]+h(-(w)*-(w)*theta*[ti])


TypeError: 'int' object is not subscriptable

In [90]:
for theta in range(5):
        theta[ti+1]=theta[ti]+h*(v[ti])

TypeError: 'int' object is not subscriptable